f_backup=$1
f_seq=$2

#mv "/home/houfek/Work/NGS-DATA-FAIRIFICATION/playground/muni-sc/210121_M02340_0246_000000000-JDH8T" "/home/houfek/Work/NGS-DATA-FAIRIFICATION/playground/seq/TRANSFER/."

 cp -r -f "${f_backup}/Data/RTALogs" "${f_seq}/Data/."
 cp -r -f "${f_backup}/Data/Intensities/L001" "${f_seq}/Data/Intensities/."
 cp -r -f "${f_backup}/Data/Intensities/BaseCalls" "${f_seq}/Data/Intensities/."
 cp -r -f "${f_backup}/Thumbnail_Images" "${f_seq}/."
 cp -r -f "${f_backup}/Recipe" "${f_seq}/."
echo "Big images done"
 cp -f "${f_backup}/Data/Intensities/RTAConfiguration.xml" "${f_seq}/Data/Intensities/RTAConfiguration.xml"
 cp -f "${f_backup}/Data/Intensities/BaseCalls/SampleSheet.csv" "${f_seq}/Data/Intensities/BaseCalls/SampleSheet.csv"
 cp -f "${f_backup}/Data/Intensities/BaseCalls/Alignment/SampleSheetUsed.csv" "${f_seq}/Data/Intensities/BaseCalls/Alignment/SampleSheetUsed.csv"
 cp -f "${f_backup}/Data/Intensities/BaseCalls/Alignment/GenerateFASTQRunStatistics.xml" "${f_seq}/Data/Intensities/BaseCalls/Alignment/GenerateFASTQRunStatistics.xml"
 cp -f "${f_backup}/Basecalling_Netcopy_complete_Read1.txt" "${f_seq}/Basecalling_Netcopy_complete_Read1.txt"
 cp -f "${f_backup}/Basecalling_Netcopy_complete_Read2.txt" "${f_seq}/Basecalling_Netcopy_complete_Read2.txt"
 cp -f "${f_backup}/Basecalling_Netcopy_complete_Read3.txt" "${f_seq}/Basecalling_Netcopy_complete_Read3.txt"
 cp -f "${f_backup}/Basecalling_Netcopy_complete_Read4.txt" "${f_seq}/Basecalling_Netcopy_complete_Read4.txt"
 cp -f "${f_backup}/ImageAnalysis_Netcopy_complete_Read1.txt" "${f_seq}/ImageAnalysis_Netcopy_complete_Read1.txt"
 cp -f "${f_backup}/ImageAnalysis_Netcopy_complete_Read2.txt" "${f_seq}/ImageAnalysis_Netcopy_complete_Read2.txt"
 cp -f "${f_backup}/ImageAnalysis_Netcopy_complete_Read3.txt" "${f_seq}/ImageAnalysis_Netcopy_complete_Read3.txt"
 cp -f "${f_backup}/ImageAnalysis_Netcopy_complete_Read4.txt" "${f_seq}/ImageAnalysis_Netcopy_complete_Read4.txt"
 cp -f "${f_backup}/QueuedForAnalysis.txt" "${f_seq}/QueuedForAnalysis.txt"
 cp -f "${f_backup}/RTAComplete.txt" "${f_seq}/RTAComplete.txt"
 cp -f "${f_backup}/InterOp/IndexMetricsOut.bin" "${f_seq}/InterOp/IndexMetricsOut.bin"
 cp -f "${f_backup}/Data/Intensities/BaseCalls/Alignment/AdapterCounts.txt" "${f_seq}/Data/Intensities/BaseCalls/Alignment/AdapterCounts.txt"
 cp -f "${f_backup}/Data/Intensities/BaseCalls/Alignment/DemultiplexSummaryF1L1.txt" "${f_seq}/Data/Intensities/BaseCalls/Alignment/DemultiplexSummaryF1L1.txt"
 cp -f "${f_backup}/GenerateFASTQRunStatistics.xml" "${f_seq}/GenerateFASTQRunStatistics.xml"
 cp -f "${f_backup}/SampleSheet.csv" "${f_seq}/SampleSheet.csv"
echo "Small images done"
rm -rf "${f_seq}/Analysis"
cp -f -r "${f_backup}/Analysis" "${f_seq}/."
echo "Analysis done"

#rm -r "/home/houfek/Work/NGS-DATA-FAIRIFICATION/playground/muni-sc/OrganisedRuns/*"